// supabase project configurationdetails.

const SUPABASE_URL = "https://kdijlnaacvuicasxtfnn.supabase.co/rest/v1/";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkaWpsbmFhY3Z1aWNhc3h0Zm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5MDM0MzgsImV4cCI6MjEwMzQ3OTQzOH0.-Sitp6N_Ws7dKEzcbcFFMjAPK0-my0c3dW5W5HoBczs";